services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./postgres/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  jupyter:
    build: 
      context: ./notebooks
      args:
        DIR_WORK: "usr/src"
        ENV_YML: "environment.yaml"
        VENV: "pharma-data-science"
        REQ_DIR: "requirements"
        REQ_TXT: "dev.txt"
    image: biobr131/dashboards-collection-jupyter-dev:latest
    container_name: jupyter
    command: mamba run --name pharma-data-science jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token='' --ServerApp.base_url=/jupyter/ --ServerApp.trust_xheaders=True
    ports:
     - "8888:8888"
    volumes:
     - ./notebooks:/usr/src
    tty: true
    stdin_open: true
    depends_on:
      - postgres
  nginx:
    image: biobr131/dashboards-collection-nginx-dev:latest
    container_name: nginx
    build: ./nginx/Dockerfile.dev
    ports:
      - "80:80"
    depends_on:
      - jupyter

volumes:
  postgres_data:
