name: pharma-data-science
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - r-base
  - r-essentials
  - r-rlang
  - r-tidyverse
  - r-arrow
  - r-data.table
  - r-wgcna
  - r-seurat
  - r-anndata
  - r-irkernel
  - r-bigrquery
  - r-aws.s3
  - r-azurestor
  - r-biocmanager
  - bioconductor-biocgenerics
  - bioconductor-biocversion
  - bioconductor-biobase
  - bioconductor-deseq2
  - bioconductor-edger
  - bioconductor-monocle
  - bioconductor-clusterprofiler
  - bioconductor-org.hs.eg.db
  - bioconductor-org.mm.eg.db
  - bioconductor-org.dr.eg.db
  - bioconductor-org.rn.eg.db
  - bioconductor-mixomics
