FROM python:3.12

WORKDIR /usr/src

ARG POSTGRES_DIR
COPY ${POSTGRES_DIR} ${POSTGRES_DIR}/

ARG SERVICE_DIR
ARG REQ_DIR
COPY ${SERVICE_DIR}/${REQ_DIR} ${REQ_DIR}/
ARG REQ_TXT
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r ${REQ_DIR}/${REQ_TXT}

RUN useradd --create-home --shell /bin/bash flask
USER flask

EXPOSE 5000

CMD ["/bin/bash"]
